export const QuizActionTypes = {
  RESET_STATE: 'RESET_STATE',
  GET_QUESTIONS_REQ: 'GET_QUESTIONS_REQ',
  GET_QUESTIONS_RES: 'GET_QUESTIONS_RES',
  POST_QUIZ_REQ: 'POST_QUIZ_REQ',
  POST_QUIZ_RES: 'POST_QUIZ_RES',
  POST_CHANGE_REQ: 'POST_CHANGE_REQ',
  POST_CHANGE_RES: 'POST_CHANGE_RES',
};
